CREATE TABLE combustivel (
  ID INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL  ,
  TIPO_COMBUSTIVEL CHAR  NOT NULL  ,
  PRECO_CUSTO_LITRO DECIMAL(18,6)    ,
  PRECO_VENDA_LITRO DECIMAL(18,6)    ,
  TAXA_IMPOSTO DECIMAL(18,6)      ,
PRIMARY KEY(ID));




CREATE TABLE tanque (
  ID INTEGER  NOT NULL  ,
  ID_COMBUSTIVEL INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_COMBUSTIVEL)
    REFERENCES combustivel(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX tangue_FKIndex1 ON tanque (ID_COMBUSTIVEL);



CREATE TABLE bomba (
  ID INTEGER  NOT NULL  ,
  ID_TANQUE INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL    ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_TANQUE)
    REFERENCES tanque(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX bomba_FKIndex1 ON bomba (ID_TANQUE);



CREATE TABLE abastecimento_detalhe (
  ID INTEGER  NOT NULL  ,
  ID_BOMBA INTEGER  NOT NULL  ,
  VALOR_LITRO DECIMAL(18,6)    ,
  QUANTIDADE_ABASTECIDA DECIMAL(18,6)    ,
  TOTAL_ABASTECIDO DECIMAL(18,6)    ,
  IMPOSTO_TAXA DECIMAL(18,6)    ,
  IMPOSTO_VALOR DECIMAL(18,6)    ,
  DATA_ABASTECIMENTO DATE    ,
  HORA_ABASTECIMENTO TIME      ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(ID_BOMBA)
    REFERENCES bomba(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX abastecimento_detalhe_FKIndex2 ON abastecimento_detalhe (ID_BOMBA);




