CREATE TABLE combustivel (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DESCRICAO VARCHAR(40)  NOT NULL  ,
  TIPO_COMBUSTIVEL CHAR  NOT NULL   COMMENT 'G - Gasolina | D - Diesel' ,
  PRECO_CUSTO_LITRO DECIMAL(18,6)  NULL  ,
  PRECO_VENDA_LITRO DECIMAL(18,6)  NULL  ,
  TAXA_IMPOSTO DECIMAL(18,6)  NULL    ,
PRIMARY KEY(ID));




CREATE TABLE tanque (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  ID_COMBUSTIVEL INTEGER UNSIGNED  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL    ,
PRIMARY KEY(ID)  ,
INDEX tangue_FKIndex1(ID_COMBUSTIVEL),
  FOREIGN KEY(ID_COMBUSTIVEL)
    REFERENCES combustivel(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE bomba (
  ID INTEGER UNSIGNED ZEROFILL  NOT NULL   AUTO_INCREMENT,
  ID_TANQUE INTEGER UNSIGNED  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL    ,
PRIMARY KEY(ID)  ,
INDEX bomba_FKIndex1(ID_TANQUE),
  FOREIGN KEY(ID_TANQUE)
    REFERENCES tanque(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE abastecimento_detalhe (
  ID INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  ID_BOMBA INTEGER UNSIGNED ZEROFILL  NOT NULL  ,
  VALOR_LITRO DECIMAL(18,6)  NULL  ,
  QUANTIDADE_ABASTECIDA DECIMAL(18,6)  NULL  ,
  TOTAL_ABASTECIDO DECIMAL(18,6)  NULL  ,
  IMPOSTO_TAXA DECIMAL(18,6)  NULL  ,
  IMPOSTO_VALOR DECIMAL(18,6)  NULL  ,
  DATA_ABASTECIMENTO DATE  NULL  ,
  HORA_ABASTECIMENTO TIME  NULL    ,
PRIMARY KEY(ID)  ,
INDEX abastecimento_detalhe_FKIndex2(ID_BOMBA),
  FOREIGN KEY(ID_BOMBA)
    REFERENCES bomba(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);




